### ISSUE TITLE
Issue with Slot Config for Preprod

### ISSUE THREAD

**Issue by jeffhappily** [spacebudz/lucid#117]
I was trying to construct and submit a transaction that includes this
```js
.validFrom(Date.now())
```
But I got an error saying
```
ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SJust (SlotNo 12718433), invalidHereafter = SNothing}) (SlotNo 12718432))))])
```

This _seems_ to suggest that Lucid converts the time to slot differently than Blockfrost does, which _could_ be an issue with the Slot Config. However I am not sure what's the root cause of this and want to get some help.

**Comment by TotallyNotChase** [comment]
Does this happen often? Could you log the result of `Date.now()` when this does happen?

**Comment by alessandrokonrad** [comment]
> .validFrom(Date.now())

If you try this often enough you transaction you transaction will eventually be submitted. I think overall there is a little precision error. But I'm actually not sure if on the Lucid or node side. Because you have this behaviour on every network, not just Preprod.

But you see the difference is only 1 slot: `12718433` vs `12718432`. That's extremely close.

**Comment by jeffhappily** [comment]
@TotallyNotChase It happens occasionally, I haven't been able to reproduce this consistently.

@alessandrokonrad Trying a few more times does make it work, I'll close this issue for now until I can reproduce the issue consistently, or figure out what's the root cause of this.
